[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/manage-sellers"
  to = "/.netlify/functions/manage-sellers"
  status = 200